config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'sessions#new'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  get 'admin/users' => 'admin/users#index'
  get 'admin/users/:id' => 'admin/users#show', as: :admin_user_view
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:new,:create,:edit], as: :activate
  get 'admin/blockings' => 'admin/blockings#index'
  get 'admin/blockings/:category/:id' => 'admin/blockings#new', as: :admin_block
  post 'admin/blockings/:category/:id' => 'admin/blockings#create', as: :admin_block_submit
  put 'admin/blockings/:id/unblock' => 'admin/blockings#unblock', as: :admin_block_unblock

end

app/models/blocking.rb
class Blocking < ActiveRecord::Base

  belongs_to :blocker, :class_name => 'User', :foreign_key => 'blocked_by'
  CATEGORY_USER = 1
  CATEGORY_IP_ADDRESS = 2
end

app/controllers/admin/blockings_controller.rb
class Admin::BlockingsController < AdminController

  def index
    @blockings = Blocking.all
  end

  def new
    @blocking = Blocking.new
  end

  def create
    @blocking = Blocking.new(blocking_params)
    if params[:blocking][:block_category].to_i == Blocking::CATEGORY_USER
      user = User.find(params[:id])
      if user
        user.block_user
        user.save
        @blocking.current_status = true
      end
    elsif params[:blocking][:block_category].to_i == Blocking::CATEGORY_IP_ADDRESS
      @blocking.current_status = true
    end
    if @blocking.save
      flash.now[:success] = "Blocked Successfully"
      redirect_to admin_users_path
    else
      flash.now[:error] = "Something went wrong."
      redirect_to admin_users_path
    end
  end

  def unblock
    @blocking = Blocking.find(params[:id])
    if @blocking.block_category == Blocking::CATEGORY_USER
      user = User.find(@blocking.block_param)
      if user
        user.unblock_user
        user.save
        @blocking.current_status = false
      end
    end
    if @blocking.save
      flash.now[:success] = "Unblocked Successfully"
      redirect_to admin_users_path
    else
      flash.now[:error] = "Something went wrong."
      redirect_to admin_users_path
    end
  end

  private
  def blocking_params
    params.require(:blocking).permit(:block_category,:block_type, :blocked_by, :block_param, :reason,)
  end

end

app/views/admin/blockings/_form.html.erb
<%= form_for(:blocking,:url => admin_block_submit_path, :html => {:class=>'form-horizontal'}) do |f| %>
    <div class="form-group">
      <%= f.label :block_category, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :block_category, :value => params[:category] , :class => 'form-control', :readonly => true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :block_type, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :block_type , :class => 'form-control' %>
      </div>
    </div>
    <%= f.hidden_field :blocked_by, :value => session[:user_id], :class => 'form-control' %>
    <div class="form-group">
      <%= f.label :block_param, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_field :block_param, :value => params[:id] , :class => 'form-control', :readonly => true %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :reason, :class => 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_area :reason, :class => 'form-control',size: "300" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6">
        <%= f.submit "Block", :class => 'btn btn-default' %> | <%= link_to "Back", admin_users_path , :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/admin/blockings/index.html.erb
<% if @blockings.present? %>
    <table class="table table-condensed">
      <thead>
      <tr>
        <th>#</th>
        <th>Category</th>
        <th>Type</th>
        <th>Param</th>
        <th>Reason</th>
        <th>Current Status</th>
        <th>Blocked By</th>
      </tr>
      </thead>
      <tbody>
      <% @blockings.each_with_index do |blocking,i| %>
          <tr>
            <th scope="row"><%= i+1 %></th>
            <td><%= blocking.block_category %></td>
            <td><%= blocking.block_type %></td>
            <td><%= blocking.block_param %></td>
            <td><%= blocking.reason %></td>
            <td><%= blocking.current_status.to_s %></td>
            <td><%= blocking.blocker.username %></td>
            <td><%= link_to 'Unblock', admin_block_unblock_path(blocking.id), method: :put if blocking.current_status %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>

app/views/admin/blockings/new.html.erb
<%= render 'form' %>

app/views/admin/blockings/show.html.erb
<% if @blocking.present? %>
    <% @blocking.attributes.each do |blocking_data|%>
        <div class="row placeholders">
          <div class="col-xs-6 col-sm-3 placeholder">

            <h4><%= blocking_data.first%></h4>
            <span class="text-muted"><%= blocking_data.second%></span>
          </div>
        </div>
    <% end %>
<% end %>