config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'sessions#new'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  get 'admin/users' => 'admin/users#index'
  get 'admin/users/:id' => 'admin/users#show', as: :admin_user_view
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:new,:create,:edit], as: :activate
  get 'admin/blockings' => 'admin/blockings#index'
  get 'admin/blockings/:category/:id' => 'admin/blockings#new', as: :admin_block
  post 'admin/blockings/:category/:id' => 'admin/blockings#create', as: :admin_block_submit
  put 'admin/blockings/:id/unblock' => 'admin/blockings#unblock', as: :admin_block_unblock

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_create :create_activation_digest
  before_save :downcase_email

  has_many :roles
  has_many :login_attempts

  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 8 }, allow_blank: true

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def resend_activation_mail
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
    self.save
    self.send_activation_email
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def block_user
    update_attribute(:blocked,true)
    update_attribute(:blocked_at, Time.zone.now)
  end

  def unblock_user
    update_attribute(:blocked,false)
  end

  def blocking_id
    Blocking.find_by(:block_param => self.id, :block_category => Blocking::CATEGORY_USER, :current_status => true ).id
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private
  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if Rails.env.development?
          user.activate
          log_in user
          flash.now[:success] = "Account activated!"
          redirect_to user
      else
        @user.send_activation_email
        flash.now[:success] = "Activation mail sent to your mail id. Please activate your account."
        redirect_to new_user_path
      end
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password,
                                 :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<% if @users.present? %>
<table class="table table-condensed">
  <thead>
  <tr>
    <th>#</th>
    <th>User Name</th>
    <th>Email</th>
    <th>Login Attempts</th>
    <th>Activated</th>
    <th>Blocked</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each_with_index do |user,i| %>
  <tr>
    <th scope="row"><%= i+1 %></th>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.login_attempts.count %></td>
    <td><%= user.activated.to_s %></td>
    <td><%= user.blocked.to_s %></td>
    <td><%= link_to "View User", admin_user_view_path(user.id) %> | <%= user.blocked? ? (link_to "Unblock User", admin_block_unblock_path(:id => user.blocking_id), :class => 'btn btn-default', method: :put) : (link_to "Block User", admin_block_url(:category => Blocking::CATEGORY_USER, :id => user.id), :class => 'btn btn-default') %></td>
  </tr>
  <% end %>
  </tbody>
</table>
    <% content_for :head do %>
        <div>Welcome <%= current_user %>  </div>
    <% end %>
<% end %>

app/views/admin/users/show.html.erb
<div class="row placeholders">
  <div class="col-xs-6 col-sm-3 placeholder">

    <h4>Username</h4>
    <span class="text-muted"><%= @user.username %></span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">

    <h4>Email</h4>
    <span class="text-muted"><%= @user.email %></span>
  </div>
</div>
<div class="row placeholders">
  <div class="col-xs-6 col-sm-3 placeholder">

    <h4>Login Attempts</h4>
    <span class="text-muted"><%= @user.login_attempts.count %></span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">

    <h4>Successful Attempts</h4>
    <span class="text-muted"><%= @user.login_attempts.where(:success => true).count %></span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">

    <h4>Failed Attempts</h4>
    <span class="text-muted"><%= @user.login_attempts.where(:success => false).count %></span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <%= link_to "Back", admin_users_path , :class => 'btn btn-default' %> | <%= @user.blocked? ? (link_to "Unblock User", admin_block_unblock_path(:id => @user.blocking_id), :class => 'btn btn-default', method: :put) : (link_to "Block User", admin_block_url(:category => Blocking::CATEGORY_USER, :id => @user.id), :class => 'btn btn-default') %>
  </div>
</div>
<% if @user.login_attempts.present? %>
    <table class="table table-condensed">
      <thead>
      <tr>
        <th>#</th>
        <th>IP Address</th>
        <th>Country</th>
        <th>City</th>
        <th>Region</th>
        <th>Success</th>
      </tr>
      </thead>
      <tbody>
      <% @user.login_attempts.each_with_index do |attempt,i| %>
          <tr>
            <th scope="row"><%= i+1 %></th>
            <td><%= attempt.ip_address %> | <%= link_to "Block IP Address", admin_block_url(:category => Blocking::CATEGORY_IP_ADDRESS, :id => attempt.ip_address) %></td>
            <td><%= attempt.country_name %></td>
            <td><%= attempt.city_name %></td>
            <td><%= attempt.real_region_name %></td>
            <td><%= attempt.success.to_s %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>