config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'sessions#new'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'

  get 'admin/users' => 'admin/users#index'
  get 'admin/users/:id' => 'admin/users#show', as: :admin_user_view
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:new,:create,:edit], as: :activate
  get 'admin/blockings' => 'admin/blockings#index'
  get 'admin/blockings/:category/:id' => 'admin/blockings#new', as: :admin_block
  post 'admin/blockings/:category/:id' => 'admin/blockings#create', as: :admin_block_submit
  put 'admin/blockings/:id/unblock' => 'admin/blockings#unblock', as: :admin_block_unblock

end

app/views/layouts/_developer_console.html.erb
<%= debug params%>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Login system designed by Vasandkumar.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">Login System</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%=root_path%>">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <p class="navbar-text navbar-right">Signed in as <%= link_to @current_user.username, @current_user, :class => 'navbar-link' %>  <%= link_to "Log out", logout_path, method: "delete", :class => 'navbar-link' %></p>
            <% if is_admin? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'Users', admin_users_path %></li>
                    <li><%= link_to 'Blockings', admin_blockings_path %></li>
                  </ul>
                </li>
            <% end %>
        <% else %>
            <li><a href="<%=login_path%>">Login</a></li>
        <% end %>

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoginSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= render 'layouts/header' %>
<div id="main-container" class="container-fluid">
  <%= flash_messages %>
  <div class="row">
    <div id="main-content" class="col-xs-12">
      <%= yield  %>

    </div>
  </div>
</div>

<%= render 'layouts/developer_console' if Rails.env.development?%>
<%= render 'layouts/footer' %>
</body>
</html>